services:
  api:
    build: ./
    networks:
      - cart-paypal
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
    working_dir: ./:/usr/src/app
    depends_on:
      - postgres
      
  postgres:
    image: postgres:17.2-alpine3.21
    networks:
      - cart-paypal
    ports:
      - "8080:8080"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1O94NanaTdYKsU4F
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  cart-paypal:
    driver: bridge

volumes:
  postgres-data:
    driver: local
    
